### ISSUE TITLE
Enshrouded World has an install button that does nothing

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch#1206]
Enshrouded World https://brndx.itch.io/enshrouded-world gives me an install button in the itch client, but upon pressing it nothing happens. It says Downloading and then just goes back to Install.

Possibly due to my press account? Something might be not setup correctly on it.

**Comment by fasterthanlime** [comment]
They're using external links hosted on Google drive, that's not a supported setup. I'll get in touch with them by e-mail.

**Comment by fasterthanlime** [comment]
The developer pushed a full build using butler, so it should be working now.

(It's 7GB though, have fun!)

**Comment by LiamDawe** [comment]
Hmm, still the same thing here, some kind of itch app cache maybe?

**Comment by fasterthanlime** [comment]
The demo is still on gdrive, can you tell from the itch app logs which it's downloading? (an upload id would be enough to identify it)

**Comment by LiamDawe** [comment]
Log here that should have it: https://pastebin.com/5ERYF74q
