### ISSUE TITLE
YUM repository yield GPG signature error

### ISSUE THREAD

**Issue by CyberKiller40** [itchio/itch#254]
You provide a Linux version using a non-standard package format (deb). As the Linux Standards Base states,the correct way to provide 3rd party software is via an rpm package or a binary installer.
http://refspecs.linux-foundation.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/swinstall.html#SWINSTALL-INTRO

I guess a compressed binary (tar.whatever) would be also ok. Also: a 64 bit version would be also very nice (not many GNU/Linux users use a 32bit OS any more).

Debs might seem to be ok, cause they are used by the seemingly popular distros like Debian, but they are not usable in most distributions (top 3 distro families are debian, redhat and suse, only 1 of them uses debs). Rpm on the other hand is ok in every distro that wants to remain compatible with standards.

**Comment by fasterthanlime** [comment]
https://github.com/itchio/itch/releases contains both 32-bit & 64-bit deb _and rpm_.

Additionally, those are available in repositories, cf. the changelog at https://github.com/itchio/itch/releases/tag/v0.11.3

That said, they should be listed on itch.io/app, just opened an issue for that: https://github.com/leafo/itch.io/issues/300

**Comment by CyberKiller40** [comment]
OK, I didn't know about that. That really should be listed on the downloads page on itch.io

**Comment by CyberKiller40** [comment]
The rpm packages are missing.

I noticed that for a while the rpm repository was throwing gpg errors so I thought to check on the site for an update about it. And here I see the rpm packages are gone completely. :-(

**Comment by fasterthanlime** [comment]
@CyberKiller40 can you expand on "they're gone?" the bintray repository is still here: https://bintray.com/itchio/rpm — and contains packages for both 'itch' (the stable version) and 'itch_canary' (the unstable version).

what did happen at some point is: some unstable packages were mistakenly pushed as stable packages. Hence, I removed those packages & re-pushed them to the appropriate place. Maybe that's what you're seeing? It's really hard to tell without more details.

**Comment by CyberKiller40** [comment]
Apparently that was the source of the repo problem, the messages I was getting in effect were saying that the gpg signature of the repository is not valid. Now that I added this repo again (after removing it an hour ago), the message about a faulty gpg signature is still there:

> Signature verification failed for file 'repomd.xml' from repository 'itch'.
> Warning: This might be caused by a malicious change in the file!

(I did trust the gpg key)

As for the missing rpms - I looked at itch.io/app and there was no mention of them there, the download gives only a deb, nor at the releases page on github. Hence I thought they were gone. 

(edit: after browsing through a couple of pages of unstable releases I got to the stable version which does have an rpm linked, so sorry, I was too hasty, but the repo problem is real)

**Comment by fasterthanlime** [comment]
> As for the missing rpms - I looked at itch.io/app and there was no mention of them there, the download gives only a deb, nor at the releases page on github. Hence I thought they were gone.

:( those are all unfortunate circumstances. I've been writing an app manual with proper install instructions: https://docs.itch.ovh/itch/master/installing/linux/fedora.html — we'll update the itch.io/app page to link to that.

As for the faulty gpg signature, it seems out of our hands, bintray does the signing. Hopefully will get resolved once we push a new stable version, in the next few days

**Comment by CyberKiller40** [comment]
OK, will check after a new version is out.

As for instructions, you can include instructions for OpenSUSE like this:

```
sudo zypper addrepo -f https://dl.bintray.com/itchio/rpm itch
sudo rpm --import https://dl.itch.ovh/archive.key
```

That's the way I use it.

**Comment by fasterthanlime** [comment]
Is `zypper` available on all rpm-based distros? I might add it as instructions for OpenSUSE users :)

**Comment by CyberKiller40** [comment]
Sadly no, zypper is suse-specific (so it's in OpenSUSE, SUSE Linux Enterprise and the few derivatives), but it's compatible with yum format repositories. It probably can also work with .repo files that you give for RedHat (zypper addrepo /path/to/file.repo) but I didn't check that cause it's faster to add by the url.

BTW: the gpgkey import line is optional - suse asks the user if the key is trusted on the first package refresh from a repository.

BTW2: despite both using rpms and contrary to the popular opinion suse and redhat distro families are not connected to each other. Most rpms being standard enough work across both of them as these distros follow LSB, but that is not always the case. The itch app works ok so far though.

**Comment by fasterthanlime** [comment]
@CyberKiller40 out of curiosity, if you install `itch_canary` with the current repos, do you get a GPG error ?

**Comment by CyberKiller40** [comment]
The gpg error is during the repo listing/refreshing (and it's quite annoying cause it blocks packagekit updates). It shows even if none of the itch packages are installed.

**Comment by CyberKiller40** [comment]
I manually downloaded the repomd.xml, signature and the key, and when trying to verify this is what I get:

```
gpg --verify ./repomd.xml.asc 
gpg: Signature made Wed Apr 13 22:27:12 2016 CEST using RSA key ID 0949002B
gpg: BAD signature from "Amos Wenger <amoswenger@gmail.com>"
```

This would mean that the repomd.xml got changed after it was signed. You should ask this Amos Wenger person to sign the repository again. …… ah, that's you! ;-) This should make the process even faster ;-).

**Comment by fasterthanlime** [comment]
Well.. I didn't sign anything on April 13 2016 :/

Bintray is generating those itself, so I'm not sure exactly how to fix it... Apparently we're not the only ones affected https://github.com/sbt/sbt-launcher-package/issues/93

**Comment by CyberKiller40** [comment]
Maybe you could get in touch with Bintray then, cause something is definitely not good with this process.

**Comment by fasterthanlime** [comment]
I did get in touch with Bintray support, and they were able to reproduce the issue! Will update with progress.

<img width="762" alt="screen shot 2016-04-15 at 11 13 08" src="https://cloud.githubusercontent.com/assets/7998310/14556959/11a0d83a-02fb-11e6-8ef0-6c25889a8f04.png">

**Comment by fasterthanlime** [comment]
Bintray folks say a fix is going to be out in the next few days & they'll get back to me when it's out.

**Comment by CyberKiller40** [comment]
Confirm this is fixed and no longer throws errors when updating package lists + proof from gpg:

```
LANG=en gpg --verify ./repomd.xml.asc 
gpg: Signature made Tue Apr 19 20:40:39 2016 CEST using RSA key ID 0949002B
gpg: Good signature from "Amos Wenger <amoswenger@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 299A 4AF3 6BA6 8676 67E4  F697 3407 E33E 0949 002B
```

Thanks! :-)

**Comment by fasterthanlime** [comment]
Yup they got back to me, just hadn't had a chance to relay the info here yet. Glad it's fixed!

**Comment by babineaum** [comment]
I am still seeing this issue
Is there something i need to do in order to get my repo def updated?

I run 
`yum install sbt`
after putting this in my repo file 
`#bintray--sbt-rpm - packages by  from Bintray`
`[bintray--sbt-rpm]`
`name=bintray--sbt-rpm`
`baseurl=http://dl.bintray.com/sbt/rpm`
`repo_gpgcheck=0`
`enabled=1`

and im getting this as an error

`Package sbt-0.13.9.rpm is not signed`

**Comment by babineaum** [comment]
seems strange that we are getting a signature error when repo_gpgcheck is disabled.

**Comment by fasterthanlime** [comment]
@babineaum are you sure you're in the right issue tracker? I don't think we distribute any packages for the scala build tool ;) You might want to get in touch with bintray support: https://bintray.com/

**Comment by babineaum** [comment]
Ok, mistook the conversation above for a discussion on getting Bintray to fix their repo. Didn't know if you signed the rpms or they did.
