### ISSUE TITLE
TypeError: res.games.map is not a function

### ISSUE THREAD

**Issue by wbrbr** [itchio/itch#64]
When I click on the Dashboard button in the sidebar I get this error
- I'm running ArchLinux. 
- Electron is up to date. 
- Node version 5.1.0
- I own no games and have no games installed  

Full error dump:

```
Unhandled rejection TypeError: res.games.map is not a function
    at /home/wilhem/git/itchio-app/app/stores/game-store.es6:113:24
    at done (/home/wilhem/git/itchio-app/node_modules/needle/lib/needle.js:357:7)
    at PassThrough.<anonymous> (/home/wilhem/git/itchio-app/node_modules/needle/lib/needle.js:546:9)
From previous event:
    at fetch_games (/home/wilhem/git/itchio-app/app/stores/game-store.es6:112:28)
    at /home/wilhem/git/itchio-app/app/stores/store.es6:68:5
    at /home/wilhem/git/itchio-app/app/dispatcher/app-dispatcher.es6:74:11
    at Array.forEach (native)
    at Dispatcher.dispatch (/home/wilhem/git/itchio-app/app/dispatcher/app-dispatcher.es6:71:36)
    at EventEmitter.<anonymous> (/home/wilhem/git/itchio-app/app/dispatcher/app-dispatcher.es6:87:10)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/lib/web-contents.js:85:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by fasterthanlime** [comment]
That's the ghost of #48 :/

**Comment by wbrbr** [comment]
I'm on master so the changes from [this commit](https://github.com/itchio/itchio-app/commit/ee644dccea690f807582b49f004a08ee81436215) are in my tree and I still get the error :/
Also when I click on the Owned or Installed tabs I don't get the error.

**Comment by fasterthanlime** [comment]
@nounoursheureux let me know if that fixes it for you.

That's the kind of problem that should be fixed server-side, but in the meantime, it should do :see_no_evil:

**Comment by wbrbr** [comment]
Unfortunately I still get the same error. Don't you get an error when you try to open the Dashboard tab with a new account ?

**Comment by fasterthanlime** [comment]
> Don't you get an error when you try to open the Dashboard tab with a new account ?

Nope, looks fine to me (now):

<img width="708" alt="screen shot 2015-12-01 at 19 52 37" src="https://cloud.githubusercontent.com/assets/7998310/11510662/19b01820-9865-11e5-8ac9-ab3a29f82229.png">

For comparison, checking out 0279e6525d5ae69d3479a15d89c55d913eaacb95 definitely shows the error you were talking about:

<img width="1371" alt="screen shot 2015-12-01 at 19 53 11" src="https://cloud.githubusercontent.com/assets/7998310/11510685/390ab05e-9865-11e5-95fb-6c830cbe8f75.png">

Did you run `grunt all` after fetching and completely kill off (using the application's quit menu or actually `kill`-ing the right PID), before re-launching? Otherwise it'll just bring up the old instance.

(There's other grunt tasks: the default one (just running `grunt`) will only compile newer files, and `grunt watch` will watch for file changes and recompile, I keep that one in the background)

**Comment by fasterthanlime** [comment]
Just checked, checking out 0279e6525d5ae69d3479a15d89c55d913eaacb95 definitely shows the error you were talking about:

<img width="1371" alt="screen shot 2015-12-01 at 19 53 11" src="https://cloud.githubusercontent.com/assets/7998310/11510685/390ab05e-9865-11e5-95fb-6c830cbe8f75.png">

**Comment by wbrbr** [comment]
Ok, it is actually fixed.
The problem was that instead of quitting I closed the window and did Ctrl-C in the terminal, so when I ran it again it didn't initialize. After quitting it with Ctrl-Q and relaunching it, it works :+1:

**Comment by fasterthanlime** [comment]
> After quitting it with Ctrl-Q and relaunching it, it works

Awesome :) The client is currently a bit hard to 'quit', I want to fix that (I think Ctrl-C'ing in console should quit it), but I haven't yet paid close attention to which combination of Electron events _that_ triggers.

If someone wants to submit a PR that takes care of that, [the quit logic isn't that hard to find](https://github.com/search?utf8=%E2%9C%93&q=quit+repo%3Aitchio%2Fitchio-app+path%3Aapp&type=Code&ref=advsearch&l=&l=)
